package com.example.chainmeatproducerandexporter.ArshadAnjumModel;

import com.example.chainmeatproducerandexporter.ArshadAnjumInterface.ReportGenerator;
import com.example.chainmeatproducerandexporter.commonFiles.User;

public class InventoryManager extends User implements ReportGenerator {
    private String managerId;

    public InventoryManager() {
    }

    public InventoryManager(String userId, String name, String email, String password, String role, String managerId) {
        super(userId, name, email, password, role);
        this.managerId = managerId;
    }

    public String getManagerId() {
        return managerId;
    }

    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }

    public void addApprovedBatchToInventory(MeatBatch batch, Inventory inventory) {
        if ("APPROVED".equalsIgnoreCase(batch.getQualityStatus())) {
            inventory.setTotalQuantity(inventory.getTotalQuantity() + batch.getQuantity());
        }
    }

    public void updateInventoryQuantity(Inventory inventory, int newQuantity) {
        if (newQuantity >= 0) {
            inventory.setTotalQuantity(newQuantity);
        }
    }

    @Override
    public String generateReport() {
        return "Inventory report generated by Manager ID: " + managerId;
    }

    @Override
    public void saveToFile(String filePath, String content) {
        System.out.println("Saving inventory report to: " + filePath);
    }
}