package com.example.chainmeatproducerandexporter.ArshadAnjumModel;

import com.example.chainmeatproducerandexporter.ArshadAnjumInterface.ReportGenerator;
import com.example.chainmeatproducerandexporter.commonFiles.User;

public class QualityInspector extends User implements ReportGenerator {
        private String inspectorId;

        public QualityInspector() {
        }

        public QualityInspector(String userId, String name, String email, String password, String role, String inspectorId) {
            super(userId, name, email, password, role);
            this.inspectorId = inspectorId;
        }

        public String getInspectorId() {
            return inspectorId;
        }

        public void setInspectorId(String inspectorId) {
            this.inspectorId = inspectorId;
        }

        public void approveBatch(MeatBatch batch) {
            batch.setQualityStatus("APPROVED");
            batch.setInspectorId(inspectorId);
        }

        public void rejectBatch(MeatBatch batch, String reason) {
            batch.setQualityStatus("REJECTED");
            batch.setRejectionReason(reason);
            batch.setInspectorId(inspectorId);
        }

        public void markForReinspection(MeatBatch batch, String reason) {
            batch.setQualityStatus("REINSPECTION");
            batch.setReinspectionReason(reason);
            batch.setInspectorId(inspectorId);
        }

        @Override
        public String generateReport() {
            return "Inspection report generated by Inspector ID: " + inspectorId;
        }

    @Override
    public void saveToFile(String filePath, String content) {
        System.out.println("Saving inspection report to: " + filePath);
    }
}
